### ISSUE TITLE
Helmholtz EoS external functions not available in NGCC Example

### ISSUE THREAD

**Issue by AlexNoring** [IDAES/examples#121]
The NGCC example flowsheet is displaying an error on the webpage.

[NGCC Baseline and Turndown](https://idaes-examples.readthedocs.io/en/latest/active/power_gen/ngcc/ngcc_doc.html)

```
2024-05-28 17:17:05 [ERROR] idaes.core.base.process_block: Failure in build: fs.gt.prop_water
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/idaes-examples/envs/latest/lib/python3.8/site-packages/idaes/core/base/process_block.py", line 41, in _rule_default
    b.build()
  File "/home/docs/checkouts/readthedocs.org/user_builds/idaes-examples/envs/latest/lib/python3.8/site-packages/idaes/models/properties/general_helmholtz/helmholtz_functions.py", line 1441, in build
    raise RuntimeError("Helmholtz EoS external functions not available")
RuntimeError: Helmholtz EoS external functions not available
```

**Comment by andrewlee94** [comment]
This may be related to #115
